### PR TITLE
Adapt for the new embla-carousel v7

### PR DESCRIPTION
**Pull request by dermotduffy**
* Adapt the wheel gestures plugin for [embla-carousel v7](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.0-rc01).
* Changes inspired by the equivalent changes in the bundled plugins for v7 ([example](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel-autoplay/src/components/index.ts)).

### CODE REVIEW

**Comment by davidjerleke** [comment]
Hi guys!

As you may have notices the lint command is failing on this branch. It's because of the plugin type imports that are used to [define the plugin map here](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel/src/components/Plugins.ts#L21-L27). I want the Embla core library to to include the plugin types (without the need to npm install all plugins) because the core library exposes the plugin API:s from its core API in [v7 like this](https://github.com/davidjerleke/embla-carousel/issues/327).

Any ideas how to achieve this with rollup?

Basically this is about how to include an external library installed in the `node_modules` directory in my end bundle. I haven't found something useful in the rollup documentation.

### Feature description
I want to achieve the following:

**My code making use of an external component:** `src/index.ts`

```ts
import { Plugin1ApiType } from 'plugin1';
import { Plugin2ApiType } from 'plugin2';

type PluginType = Plugin1ApiType | Plugin2ApiType;

export type CoreLibraryApiType = {
  plugins: {
    plugin1?: Plugin1ApiType,
    plugin2?: Plugin2ApiType,
  }
};

export function CoreLibrary(plugins: PluginType[]): CoreLibraryApiType {
  const pluginApis = plugins.reduce((pluginApis, pluginApi) => {
    return { ...pluginApis, [plugin.name]: pluginApi };
  }, {})

  return { plugins: pluginApis };
};
```

**Desired output:** `index.d.ts`

```ts
declare type Plugin1ApiType = { ... }

declare type Plugin2ApiType = { ... }

export declare type CoreLibraryApiType = {
  plugins: {
    plugin1?: Plugin1ApiType,
    plugin2?: Plugin2ApiType,
  }
};
```

**Usage:**
```ts
import CoreLibrary from 'core-library';
import { Plugin1, Plugin1ApiType } from 'plugin1';

const plugins = [Plugin1()];
const coreLibrary = CoreLibrary(plugins);

coreLibrary.plugins.plugin1?.someMethod();
```

Any help appreciated.

Best,
David

**Comment by davidjerleke** [comment]
Thanks for the response @xiel,

Initially I wanted to do something similar to your suggestion. However there's a problem I don't know how to solve with that approach. Consider this:

```ts
function EmblaCarousel<PluginsType>(
  rootNode: HTMLElement,
  options?: Partial<EmblaOptionsType>,
  plugins?: PluginsType
) {
  let activePlugins = plugins || []

 function getPlugins(): PluginsType {
   return activePlugins
 }

  return { getPlugins }
}
```

...However, as soon as the `reInit` function comes into play, this doesn't work because a reInit lets you pass new plugins which causes the initial provided PluginsType to become stale. I don't know if it's possible to have a dynamic generic type with TypeScript. The problem:

```ts
function EmblaCarousel<PluginsType>(
  rootNode: HTMLElement,
  options?: Partial<EmblaOptionsType>,
  plugins?: PluginsType
) {
  let activePlugins = plugins || []

  function reInit<PluginsType>(
    options?: Partial<EmblaOptionsType>, 
    plugins?: PluginsType
  ): void {
    activePlugins = plugins || activePlugins
  }

 function getPlugins(): PluginsType {
   return activePlugins
 }

  return { getPlugins }
}
```

Let me know if you know a way around this and thanks.

Cheers,
David

**Comment by davidjerleke** [comment]
Sorry @xiel for destroying the comment section in this PR with irrelevant stuff by the way 🙈.

**Comment by xiel** [comment]
@davidjerleke All good 👍 You're right, this does not really work well with reinit.

I'm currently drafting a different approach, seems to work so far. I think I will open a PR today and we can discuss it further there.

**Comment by xiel** [comment]
@davidjerleke Here we go: https://github.com/davidjerleke/embla-carousel/pull/335 
Let me know what you think. See you over there.

**Pull request merged**
